version: '3'
services:
  app:
    image: python:buster
    environment:
      - VPNM_API_URL=https://ssle4.ru/api
      - VPNM_TOKEN=s5F4YBJfWCPMUuaU1yYZZXo7tyu07ZjV0W8KHrK7TLRuaC7ZFdT9SvjCcIy4FDfL
    network_mode: host
    volumes:
      - /etc/apt/apt.conf:/etc/apt/apt.conf:ro
      - .:/code
    command: bash -c "apt update && apt install traceroute git -y && python3 -m pip
      install poetry && cd /code && python3 -m poetry export -o requirements.txt
      --without-hashes && python3 -m pip install -r requirements.txt && python3
      vpnmmon"
